In [2]:
import numpy as np

In [7]:
# 1-D using list/tuple

fromList_to_1dArray = np.array([10,20,30,40,50])
fromTuple_to_1dArray = np.array((1,2,3,4,5))

print(type(fromList_to_1dArray))
print(fromList_to_1dArray)

print(type(fromTuple_to_1dArray))
print(fromTuple_to_1dArray)

<class 'numpy.ndarray'>
[10 20 30 40 50]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [8]:
# 2-D
fromList_to_2dArray = np.array([[0,1,2,3,4],[5,6,7,8,9]])
fromList_to_2dArray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Numpy vs standard python

In [9]:
num_1 = [1,2,3,4,5,6,7,8,9]
num_2 = [10,11,12,13,14,15,16,17,18]

sum_list = list(map(lambda x,y: x+y, num_1,num_2))
print(sum_list)

[11, 13, 15, 17, 19, 21, 23, 25, 27]


In [10]:
np_list1 = np.array(num_1)
np_list2 = np.array(num_2)

num_sumList = np_list1 + np_list2
print(num_sumList)
print(type(num_sumList))

[11 13 15 17 19 21 23 25 27]
<class 'numpy.ndarray'>


In [12]:
# list
list1 = np.array([1,2,3,4,5])
list2 = np.array([1,2,3,4,5],dtype=float)
# tuple
array_tuple = np.array((0,5,7,8,9))
print(list1)
print(list2)
print(array_tuple)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[0 5 7 8 9]


In [13]:
# condition statement as an arg to np.array
array_list3 = list1 >= 2
print(array_list3)

[False  True  True  True  True]


In [15]:
# fetch the the actual ele
list1[array_list3]

array([2, 3, 4, 5])

In [18]:
arr1 = np.array([[0,1,2,3], [2,3,5,6]])
print(arr1)
arr2 = np.array([[10,11,12,13], [14,15,16,17]])
arr2

[[0 1 2 3]
 [2 3 5 6]]


array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [19]:
arr1 - arr2

array([[-10, -10, -10, -10],
       [-12, -12, -11, -11]])

 ## initialize np array 


In [24]:
# np.range
# range ()
incrmnt = np.arange(1,15,2)
print('incrmnt:',incrmnt)
decemnt = np.arange(50,10,-10)
print('decemnt:',decemnt)

incrmnt: [ 1  3  5  7  9 11 13]
decemnt: [50 40 30 20]


In [26]:
# zeros initialize
np.zeros(5)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
# zeros initialize
np.ones(5)
np.ones((5,5))
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
np.random.random([4,4])

array([[0.23790091, 0.98320489, 0.80626478, 0.94396083],
       [0.92947759, 0.7770982 , 0.75009609, 0.6496966 ],
       [0.63504924, 0.11606773, 0.81988198, 0.80677058],
       [0.78927973, 0.81973292, 0.69338443, 0.61653454]])

In [32]:
# 3 X 3 random
np.random.randint(1,10,(3,3))

array([[7, 3, 1],
       [4, 4, 7],
       [2, 4, 7]])

In [36]:
np.full(2,5)
np.full((2,5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [37]:
# Identity matrix
i_mat = np.eye(5,dtype=int)
i_mat

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [39]:
np.linspace(1,10,2)

array([ 1., 10.])

# Structure of Arrays

In [40]:
array1 = np.ones((5,5))
array1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
# find dtype
print(array1.dtype)
print(array1.shape)
print(array1.itemsize)
print(array1.ndim)

float64
(5, 5)
8
2
